{{- if .Values.mqApiGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-api-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: mq-api-gateway
spec:
  replicas: {{ .Values.mqApiGateway.replicas }}
  selector:
    matchLabels:
      app: mq-api-gateway
  template:
    metadata:
      labels:
        app: mq-api-gateway
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector.cpu | nindent 8 }}
      containers:
      - name: mq-api-gateway
        image: {{ .Values.registry.host }}/{{ .Values.mqApiGateway.image.repository }}:{{ .Values.mqApiGateway.image.tag }}
        imagePullPolicy: {{ .Values.mqApiGateway.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mqApiGateway.port }}
        env:
        {{- range $key, $value := .Values.mqApiGateway.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: mq-api-gateway
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: mq-api-gateway
  ports:
  - port: {{ .Values.mqApiGateway.port }}
    targetPort: {{ .Values.mqApiGateway.port }}
    nodePort: {{ .Values.mqApiGateway.nodePort }}
{{- end }}
